# Generated by Django 3.1 on 2021-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='is_subcribed',
            field=models.BooleanField(default=False),
        ),
    ]
