# Generated by Django 3.1 on 2021-11-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mycustomuser_is_subcribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
