# Generated by Django 3.0 on 2021-11-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211113_2243'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientsinrecepie',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient_in_recipe'),
        ),
    ]
